version: '3'
services:
  web:
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
  
  test:
    volumes:
      - /app/node_modules
      - .:/app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]